# Site settings
title: Memo Garcia
email: root@memogarcia.mx
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://memogarcia.mx" # the base hostname & protocol for your site
twitter_username: memowinchester
github_username:  memogarcia

# Build settings
markdown: kramdown

comments: true
