# Site settings
title: Memo Garcia
email: sirmemogarcia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://memogarcia.me" # the base hostname & protocol for your site
twitter_username: memowinchester
github_username:  memogarcia

# Build settings
markdown: kramdown

comments: true

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-63826874-1'