# Site settings
title: "Memo Garcia"
description: ""
email: memogarcia@protonmail.ch
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "http://memogarcia.mx"
author: "Guillermo Ramirez Garcia"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 
